### ISSUE TITLE
UTU_cat.json 

### ISSUE THREAD

**Issue by tintamarre** [openjusticebe/resources#1]
This json is wrongly formatted. It should be corrected : 
https://github.com/openjusticebe/resources/blob/main/json/UTU_cat.json

The source file is here : https://github.com/openjusticebe/resources/tree/main/xls

**Comment by tintamarre** [comment]
See commit https://github.com/openjusticebe/resources/commit/cf8e146fa29746f2dfa2026a6767415bf5edd783

**Comment by RRINKIN** [comment]
Suggested json structure has been pushed for discussion and validation. 

1. Validate format of the json
2. confirm if accents must be removed from file as not supported in my exported version of the json

**Comment by RRINKIN** [comment]
New version suggested. I hope this is ok.
Please keep me posted for any changes required

**Comment by tintamarre** [comment]
Merged in https://github.com/openjusticebe/resources/pull/5
